title: Punam Katariya # your name (or website title) here
key: MBA, M.Sc. Statistics, B.Sc. Mathematics, Data Science Certified
bg: blue
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3>Data Scientist | Entrupruner | Consultant </h3>
  <br><br>
#<li>
#<a href="https://www.linkedin.com/in/punamkatariya/"> View My LinkedIn Profile</a></li>
#  <br><br>
# <li><a href="https://www.upwork.com/freelancers/~010e269a82bb30c80a"> Top Rated Freelencer</a></li>
#  <br><br>
#  <li><a href="https://adatscience.com/"> Data Science Consultancy Founder</a></li>

  <a href="https://www.linkedin.com/in/punamkatariya/">LinkedIn |</a><a href="https://www.linkedin.com/in/punamkatariya/"> Upwork |</a><a href="https://adatscience.com/"> Website</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
