title: Punam Katariya, MBA, M.Sc. Statistics, B.Sc. Mathematics, Data Science Certified # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Entrupruner, Consultant 
  <br><br>
  <li>
  <a href="https://www.linkedin.com/in/punamkatariya/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.upwork.com/freelancers/~010e269a82bb30c80a"> Top Rated Freelencer</a>
  <br><br>
  <a href="https://adatscience.com/"> Data Science Consultancy Founder</a>
  <br><br>
  </li>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
